language: node_js
node_js:
    - "12"
script:
    - echo '***Build Starts***'
    - echo '***Installing Dependencies'
    - yarn install
    - echo "***Running Tests***"
    - yarn test
    - yarn run coveralls
    - yarn build